[[redirects]]
  from = "/success-contact/"
  to = "/success/"
  status = 301
  force = true

  #old site redirects

[[redirects]]
  from = "/portfolio/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/corp_light"
  to = "/corplight"
  status = 301
  force = true